import { Geist, Geist_Mono, Poppins, Volkhov } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ['400','500','600']
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ['700','500','600','400']
});
const volkhov = Volkhov({
  subsets: ["latin"],
  weight: ['700']
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${poppins.className} ${volkhov.className} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
